api_client:
  http:
    timeout: 10s
    increase: 1.2
    decrease: 2.0
    max_rate: 5.0
    min_rate: 0.1
    burst: 2
  sources:
    sources_ids_provider: https://dikidi.net/550001?p=1.pi-ssm-sd&s=7937920&rl=0_0
    slots_source: https://dikidi.net/ru/mobile/ajax/newrecord/get_datetimes/?company_id=550001
subscription_service:
  deduplicator:
    key_prefix: slot
    ttl: 5m
